### ISSUE TITLE
Cannot connect to my diffgram running locallly 

### ISSUE THREAD

**Issue by JKYang01** [diffgram/python-sdk#64]
Hi diffgram team,
I have installed the diffgram which is using docker containers handling the back-end, and the port is localhost:8085. 
Since I am trying to build a workflow for a team to do datalabeling. I want to use configarations to automatically generate projects, download files from AWS s3 bucket to diffgram, map up the pre-label files etc.  I found there is diffgram SDK so I am trying to use diffgram SDK to do the work. However I was stuck at very first step, I cannot connect my local-running diffgram using the api keys ( which I got from my local website) 
 here is the screen shot of my webpage
![Screenshot from 2024-07-29 20-15-09](https://github.com/user-attachments/assets/5b279f46-a87e-469a-9ce6-219ed4af544f)

here is the code I tested running 
```import os
from diffgram import Project
from dotenv import load_dotenv
# Load environment variables from .env file
load_dotenv()

project = Project(
  host = "http://localhost:8085",
  project_string_id = os.getenv("project_string_id"),
  client_id = os.getenv("client_id"),
  client_secret = os.getenv("client_secret"))
```

   here is the error message 
  ```
Traceback (most recent call last):
  File "/home/bluespinach/miniconda3/envs/diffgram/lib/python3.10/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/home/bluespinach/miniconda3/envs/diffgram/lib/python3.10/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/home/bluespinach/miniconda3/envs/diffgram/lib/python3.10/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bluespinach/miniconda3/envs/diffgram/lib/python3.10/site-packages/urllib3/connectionpool.py", line 715, in urlopen
    httplib_response = self._make_request(
  File "/home/bluespinach/miniconda3/envs/diffgram/lib/python3.10/site-packages/urllib3/connectionpool.py", line 416, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/home/bluespinach/miniconda3/envs/diffgram/lib/python3.10/site-packages/urllib3/connection.py", line 244, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/home/bluespinach/miniconda3/envs/diffgram/lib/python3.10/http/client.py", line 1283, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/home/bluespinach/miniconda3/envs/diffgram/lib/python3.10/http/client.py", line 1329, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/home/bluespinach/miniconda3/envs/diffgram/lib/python3.10/http/client.py", line 1278, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/home/bluespinach/miniconda3/envs/diffgram/lib/python3.10/http/client.py", line 1038, in _send_output
    self.send(msg)
  File "/home/bluespinach/miniconda3/envs/diffgram/lib/python3.10/http/client.py", line 976, in send
    self.connect()
  File "/home/bluespinach/miniconda3/envs/diffgram/lib/python3.10/site-packages/urllib3/connection.py", line 205, in connect
    conn = self._new_conn()
  File "/home/bluespinach/miniconda3/envs/diffgram/lib/python3.10/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x73013a12cd90>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bluespinach/miniconda3/envs/diffgram/lib/python3.10/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
  File "/home/bluespinach/miniconda3/envs/diffgram/lib/python3.10/site-packages/urllib3/connectionpool.py", line 799, in urlopen
    retries = retries.increment(
  File "/home/bluespinach/miniconda3/envs/diffgram/lib/python3.10/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=8085): Max retries exceeded with url: /api/project/laobocai/user/legacy/working_dir/view (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x73013a12cd90>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bluespinach/workplace/diffgram_sdk/diffgram_project.py", line 8, in <module>
    project = Project(
  File "/home/bluespinach/miniconda3/envs/diffgram/lib/python3.10/site-packages/diffgram/core/core.py", line 84, in __init__
    self.set_default_directory(directory = self.directory)
  File "/home/bluespinach/miniconda3/envs/diffgram/lib/python3.10/site-packages/diffgram/core/core.py", line 340, in set_default_directory
    default_directory = self.directory.get()
  File "/home/bluespinach/miniconda3/envs/diffgram/lib/python3.10/site-packages/diffgram/core/directory.py", line 330, in get
    response = self.client.session.get(
  File "/home/bluespinach/miniconda3/envs/diffgram/lib/python3.10/site-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
  File "/home/bluespinach/miniconda3/envs/diffgram/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/bluespinach/miniconda3/envs/diffgram/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/home/bluespinach/miniconda3/envs/diffgram/lib/python3.10/site-packages/requests/adapters.py", line 700, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8085): Max retries exceeded with url: /api/project/laobocai/user/legacy/working_dir/view (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x73013a12cd90>: Failed to establish a new connection: [Errno 111] Connection refused'))
```

**Comment by JKYang01** [comment]
never mind I fixed it, just make sure the server is on! lol

**Comment by anthony-chaudhary** [comment]
Glad it resolved! 😊
